version: "1.0"

services:
  DB:
    image: postgres:17.4
    container_name: DB
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data

  API:
    image: python:3.9
    container_name: API
    working_dir: /app
    volumes:
      - backend_data:/app
    command: >
      bash -c "apt-get update &&
               apt-get install git &&
               git clone https://github.com/Ki-re/Finance-Manager-API . &&
               /usr/local/bin/python -m pip install --upgrade pip && 
               cd /app &&
               pip3 install -r requirements.txt &&
               chmod +x start.sh && 
               exec ./start.sh"
    ports:
      - "8001:8001"
    depends_on:
      - DB
  
  Front:
    image: node:23-alpine
    container_name: Front
    command: >
      sh -c "apk update &&
             apk add git &&
             git clone https://github.com/Yearsuck/Finance-Manager-Frontend &&
             npm install -g http-server &&
             npm install -g serve &&
             cd /app &&
             npm install &&
             npm run build &&
             serve -s dist -l 80"
    working_dir: /app
    volumes:
      - frontend_data:/app
    ports:
      - "80:80"
    depends_on:
      - API